/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JournalsRouteImport } from './routes/journals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UpdateRouteImport } from './routes/update'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AdminProjectsNewRouteImport } from './routes/admin.projects.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProjectsIdJournalRouteImport } from './routes/projects.$id.journal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalsRoute = JournalsRouteImport.update({
  id: '/journals',
  path: '/journals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdateRoute = UpdateRouteImport.update({
  id: '/update',
  path: '/update',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/admin/staff',
  path: '/admin/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const AdminProjectsNewRoute = AdminProjectsNewRouteImport.update({
  id: '/admin/projects/new',
  path: '/admin/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdJournalRoute = ProjectsIdJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => ProjectsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/update': typeof UpdateRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/staff': typeof AdminStaffRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id/journal': typeof ProjectsIdJournalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/update': typeof UpdateRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/staff': typeof AdminStaffRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id/journal': typeof ProjectsIdJournalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/dashboard': typeof DashboardRoute
  '/journals': typeof JournalsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/update': typeof UpdateRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/staff': typeof AdminStaffRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/admin/projects/new': typeof AdminProjectsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/projects/$id/journal': typeof ProjectsIdJournalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/journals'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/update'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/staff'
    | '/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/projects/$id/journal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/dashboard'
    | '/journals'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/update'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/staff'
    | '/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/projects/$id/journal'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/journals'
    | '/login'
    | '/notifications'
    | '/projects'
    | '/settings'
    | '/update'
    | '/admin/audit'
    | '/admin/customers'
    | '/admin/staff'
    | '/projects/$id'
    | '/admin/projects/new'
    | '/api/auth/$'
    | '/projects/$id/journal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  DashboardRoute: typeof DashboardRoute
  JournalsRoute: typeof JournalsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  UpdateRoute: typeof UpdateRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminProjectsNewRoute: typeof AdminProjectsNewRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journals': {
      id: '/journals'
      path: '/journals'
      fullPath: '/journals'
      preLoaderRoute: typeof JournalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/update': {
      id: '/update'
      path: '/update'
      fullPath: '/update'
      preLoaderRoute: typeof UpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/admin/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/admin/projects/new': {
      id: '/admin/projects/new'
      path: '/admin/projects/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AdminProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/journal': {
      id: '/projects/$id/journal'
      path: '/journal'
      fullPath: '/projects/$id/journal'
      preLoaderRoute: typeof ProjectsIdJournalRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
  }
}

interface ProjectsIdRouteChildren {
  ProjectsIdJournalRoute: typeof ProjectsIdJournalRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdJournalRoute: ProjectsIdJournalRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  DashboardRoute: DashboardRoute,
  JournalsRoute: JournalsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  UpdateRoute: UpdateRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminProjectsNewRoute: AdminProjectsNewRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
